version: '3'

services:
  api:
    container_name: api
    restart: unless-stopped
    build: 
      dockerfile: ./dockerfile
      context: .
    volumes:
      - ./src:/usr/src/app/src
    ports:
      - ${PORT}:${PORT}
    command: ${DOCKER_COMMAND}
    depends_on: 
      - mongo
  mongo:
    container_name: mongo_db
    image: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    ports:
      - 27017:27017
    volumes:
      - "./src/db/init/:/docker-entrypoint-initdb.d/"

  mongo-express:
    container_name: mongo_express
    image: mongo-express
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_USERNAME}