version: '3'

services:
  api:
    container_name: api
    restart: unless-stopped
    build: 
      dockerfile: ./dockerfile
      context: .
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    command: npm run dev
    depends_on: 
      - mongo
  mongo:
    container_name: mongo_db
    image: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_INITDB_ROOT_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_INITDB_ROOT_PASSWORD
      MONGO_DB_USERNAME: $DB_USERNAME
      MONGO_DB_PASSWORD: $DB_PASSWORD
      MONGO_DB: $DB_NAME
      MONGO_DB_COLLECTION: $DB_COLLECTION
    ports:
      - 27017:27017
    volumes:
      - ./src/db/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh

  mongo-express:
    container_name: mongo_express
    image: mongo-express
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: $MONGO_INITDB_ROOT_USERNAME
      ME_CONFIG_MONGODB_ADMINPASSWORD: $MONGO_INITDB_ROOT_PASSWORD