@port = 5000
@baseUrl = http://localhost:{{port}}/api/
# @baseUrl = https://bulk-data-api.herokuapp.com/api
################################## QUESTIONARIES ################################
### POST /api/questionaries
POST {{baseUrl}}/questionaries
Content-Type: application/json

{
    "questionaryName": "Social",
    "questionaryDescription": "TEST",
    "questionaryAudicence": "TEST",
    "questionarySections": [
        "e23291c0-07e9-4704-aaea-d01a3be7b412"
    ]
}

### GET /api/questionaries/:id
GET {{baseUrl}}/questionaries/7d283f60-d6b1-4155-af4f-550d4eeda9ec
Content-Type: application/json

### GET /api/questionaries
GET {{baseUrl}}/questionaries
Content-Type: application/json

### GET /api/questionaries/:_questionaryId/sections/unanswered/student/:studentId
GET {{baseUrl}}/questionaries/e9a43e8c-cf42-4776-ad3c-93abebbb28c0/sections/unanswered/student/32468ba5-4c52-4a75-bb2f-e649287da878

### PUT /api/questionaries
PUT {{baseUrl}}/questionaries/e9a43e8c-cf42-4776-ad3c-93abebbb28c0
Content-Type: application/json

{
    "questionarySections": [
        "01c45996-f15f-4c1e-aba4-5153133c489a",
        "1e1a49cf-627a-49e4-8488-ec34a3945b11"
    ]
}

### DELETE /api/questionaries/:id
DELETE {{baseUrl}}/questionaries/7d283f60-d6b1-4155-af4f-550d4eeda9ec
Content-Type: application/json


################################## SECTIONS ################################
### POST /api/sections
POST {{baseUrl}}/sections
Content-Type: application/json

{
    "sectionName": "Social 2",
    "sectionDescription": "TEST",
    "sectionQuestions": ["eb837b9a-4da7-4b62-b2bf-b20685f152e7"]
}

### GET /api/sections/:id
GET {{baseUrl}}/sections/68b9c879-feb5-4b33-84c4-3ca5144cfa30
Content-Type: application/json

### GET /api/sections
GET {{baseUrl}}/sections
Content-Type: application/json

### PUT /api/sections
PUT {{baseUrl}}/sections/68b9c879-feb5-4b33-84c4-3ca5144cfa30
Content-Type: application/json

{
    "sectionName": "Socio-Economico"
}

### DELETE /api/sections/:id
DELETE {{baseUrl}}/sections/68b9c879-feb5-4b33-84c4-3ca5144cfa30
Content-Type: application/json

################################## QUESTIONS ################################
### POST /api/questions
POST {{baseUrl}}/questions
Content-Type: application/json

{
    "question": "Pregunta 1",
    "questionType": "MultipleOption",
    "questionOptions": ["1", "2", "3"]
}

### GET /api/questions/:id
GET {{baseUrl}}/questions/ada5a675-cc25-491e-a1c8-e6333536334a
Content-Type: application/json

### GET /api/questions
GET {{baseUrl}}/questions
Content-Type: application/json

### PUT /api/questions
PUT {{baseUrl}}/questions/68b9c879-feb5-4b33-84c4-3ca5144cfa30
Content-Type: application/json

{
    "sectionName": "Socio-Economico"
}

### DELETE /api/questions/:id
DELETE {{baseUrl}}/questions/68b9c879-feb5-4b33-84c4-3ca5144cfa30
Content-Type: application/json


################################## ANSWERS ################################
### POST /api/answers
POST {{baseUrl}}/questionaries/e9a43e8c-cf42-4776-ad3c-93abebbb28c0/section/01c45996-f15f-4c1e-aba4-5153133c489a/answers
Content-Type: application/json

{
    "studentId": "32468ba5-4c52-4a75-bb2f-e649287da878",
    "answers": [
    {
        "questionId": "ada5a675-cc25-491e-a1c8-e6333536334a",
        "questionAnswer": "3"
    }]
}

### GET /api/answers/:id
GET {{baseUrl}}/answers/30c44039-2261-422c-9b83-92990c64f85c
Content-Type: application/json

### GET /api/answers
GET {{baseUrl}}/answers/
Content-Type: application/json

### DELETE /api/answers/:id
DELETE {{baseUrl}}/answers/68b9c879-feb5-4b33-84c4-3ca5144cfa30
Content-Type: application/json

################################ NOTIFICATIONS ######################################
### POST /api/notifications
POST {{baseUrl}}/notifications
Content-Type: application/json

{
    "user": "6bdf63e7-14e5-40ff-955d-1ea1bf054a02",
    "message": "Notificación",
    "subject": "Notificación",
    "date": "2021-03-04T08:15:30-05:00",
    "data": {
        "URL": "http://lo_que_sea.com"
    }
}

### GET /api/notifications/:id
GET {{baseUrl}}/notifications/7690a8cf-4f83-4eb5-8bb4-ecedfe07a5e4
Content-Type: application/json

### GET /api/notifications
GET {{baseUrl}}/notifications?read=false
Content-Type: application/json

### PUT /api/notifications
PUT {{baseUrl}}/notifications/7690a8cf-4f83-4eb5-8bb4-ecedfe07a5e4
Content-Type: application/json

{
    "read": true
}
################################## TAGS ################################
### POST /api/tags
POST {{baseUrl}}/tags
Content-Type: application/json

{
    "name": "Social"
}

### GET /api/tags/
GET {{baseUrl}}/tags
Content-Type: application/json

### GET /api/tags/:id
GET {{baseUrl}}/tags/dec85d81-d201-4e00-83e0-02aefd86dc8b
Content-Type: application/json

### PUT /api/tags
PUT {{baseUrl}}/tags/dec85d81-d201-4e00-83e0-02aefd86dc8b
Content-Type: application/json

{
    "name": "Tag"
}